services:
  aiometadata:
    image: ghcr.io/cedya77/aiometadata:latest
    container_name: aiometadata
    restart: unless-stopped
    expose:
      - 3232
    env_file:
      - .env
    volumes:
      - ./aiometadata/data:/app/addon/data
    networks:
      - pangolin_frontend
      - aiometadata
    depends_on:
      aiometadata_redis:
        condition: service_healthy
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3232/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  aiometadata_redis:
    image: redis:latest
    container_name: aiometadata_redis
    restart: unless-stopped
    networks:
      - aiometadata
    expose:
      - 6379
    volumes:
      - ./aiometadata/cache:/data
    command: redis-server --appendonly yes --save 3600 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  # Created by the Pangolin stack.
  pangolin_frontend:
    external: true
  # Created by this stack. jikan attaches to it as external.
  aiometadata:
    name: aiometadata
